baseURL = "http://blog.stevenwilkin.com/"
languageCode = "en-gb"
title = "Steven Wilkin"
theme = "noteworthy"
googleAnalytics = "UA-2764682-1"

[permalinks]
post = "/:year/:month/:day/:title/"

[taxonomies]
category = "category"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 2

[params]
email = "mailto:steve@stevenwilkin.com"
twitter = "https://twitter.com/stevebiscuit"
linkedin = "https://www.linkedin.com/in/stevenwilkin/"
github = "https://github.com/stevenwilkin/"
